version: '3.8'
services:
  front:
    build:
      context: ./front/
    command: npm start
    volumes:
      - ./front/:/usr/app
      - /usr/app/node_modules
    ports: 
      - 3000:3000
    depends_on:
      - server
  server:
    build:
      context: ./server/
    command: node src/index.js
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - 8080:8080